version: '3.3'
services:
  filebeat-servername:
    container_name: filebeat-riset
    hostname: filebeat-riset
    user: root
    image: docker.elastic.co/beats/filebeat:7.15.2
    restart: always
    volumes:
      - ./config/filebeat.yml:/usr/share/filebeat/filebeat.yml
      # - /var/run/docker.sock:/var/run/docker.sock
      # - /home/docker/containers/:/var/lib/docker/containers/
      - ./logs/haproxy:/logs/haproxy
      - ./logs/erp/:/logs/erp
    environment: 
     - TZ=Asia/Jakarta
    command: filebeat -e --strict.perms=false
